# See https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates
version: 2
updates:
  # Fetch and update latest `npm` packages
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      time: '00:00'
    target-branch: dependabot
    open-pull-requests-limit: 10
    reviewers:
      - chettapong
    assignees:
      - chettapong
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      time: '00:00'
    target-branch: dependabot
    open-pull-requests-limit: 10
    reviewers:
      - chettapong
    assignees:
      - chettapong
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
